version: '3.8'

x-volumes: &volumes
  volumes:
    - ./:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

services:
  php:
    build: .
    <<: *volumes

  nginx:
    image: nginx:1.23-alpine
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - "8089:80"
    <<: *volumes
